version: '3.3'
services:
   portainer-ce:
      container_name: portainer.containers
      image: portainer/portainer-ce
      restart: always
      volumes:
         - '/var/run/docker.sock:/var/run/docker.sock'
         - './portainer_data:/portainer_data'
      networks:
         - web-secure
      ports:
         - "9000:9000"


networks:
   web-secure:
      external: true
