version: '3.3'
services:
   portainer-ce:
      container_name: portainer.containers
      image: portainer/portainer-ce
      restart: always
      volumes:
         - '/var/run/docker.sock:/var/run/docker.sock'
         - './portainer_data:/portainer_data'
      networks:
         - web-secure
      labels:
         - "traefik.enable=true"
         
         - "traefik.http.routers.portainer-secure.rule=Host(`portainer.apex-migrations.net`)"
         - "traefik.http.routers.portainer-secure.tls.certresolver=production"
         - "traefik.http.routers.portainer-secure.tls=true"
         - "traefik.http.routers.portainer-secure.entrypoints=web-secure"
         - "traefik.http.services.portainer.loadbalancer.server.port=9000" #port to the webservice
         - "traefik.http.routers.portainer-secure.middlewares=authelia-secure@docker, IP2Location@file, requestHeader@file"

networks:
   web-secure:
      external: true
